spring.application.name=processamento

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/microservice-processamento
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

#Adicione endereço e nome da fila do seu ambiente
spring.rabbitmq.addresses=# Endereço da fila Aqui
broker.queue.processamento.name=# nome da fila Aqui