spring.application.name=processamento

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/microservice-processamento
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.addresses=amqps://wvxbbocj:uFICHUQ_jT5cmLG2hg9RrVFLBop_ZLjj@leopard.lmq.cloudamqp.com/wvxbbocj
broker.queue.processamento.name=exchange.processamento