spring.application.name=processamento

server.port=8082

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/microservice-processamento}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}

spring.rabbitmq.addresses=${RABBITMQ_ADDRESSES:}
broker.queue.processamento.name=${RABBITMQ_PROCESSING_QUEUE:}
